[package]
name = "mavlink-network-node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mavlink = "0.12.2"
sx127x_lora = "0.3.1"
